- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Activa los paquetes extras para nginx de amazon linux 2
      shell: "amazon-linux-extras enable nginx1.12"
      become: yes
    - name: Install nginx
      yum:
        name: nginx
        state: latest
    - name: Restart nginx
      service: name=nginx state=restarted
      become: yes
